package com.yf.smp.app.platform;

import com.yf.smp.common.api.ApiResponse;
import java.util.List;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

@RestController
@RequestMapping("/api/v1")
public class DataManagementController {
    private final PlatformIdentityService identityService;
    private final DataManagementService service;
    public DataManagementController(PlatformIdentityService identityService, DataManagementService service) { this.identityService = identityService; this.service = service; }
    @GetMapping("/data-sources") ResponseEntity<ApiResponse<List<DataSourceResponse>>> dataSources(@RequestHeader(name="Authorization",required=false) String a,@RequestParam(required=false) String status,@RequestParam(required=false) String type){ return PlatformResponses.ok(service.dataSources(principal(a),status,type)); }
    @PostMapping("/data-sources") ResponseEntity<ApiResponse<DataSourceResponse>> createDataSource(@RequestHeader(name="Authorization",required=false) String a,@RequestBody DataSourceRequest r){ return PlatformResponses.ok(service.createDataSource(principal(a),r)); }
    @GetMapping("/data-sources/{id}") ResponseEntity<ApiResponse<DataSourceResponse>> dataSource(@RequestHeader(name="Authorization",required=false) String a,@PathVariable String id){ return PlatformResponses.ok(service.dataSources(principal(a),null,null).stream().filter(i->i.sourceId().equals(id)).findFirst().orElseThrow()); }
    @PutMapping("/data-sources/{id}") ResponseEntity<ApiResponse<DataSourceResponse>> updateDataSource(@RequestHeader(name="Authorization",required=false) String a,@PathVariable String id,@RequestBody DataSourceRequest r){ return PlatformResponses.ok(service.updateDataSource(principal(a),id,r)); }
    @PostMapping("/data-sources/{id}/test") ResponseEntity<ApiResponse<DataSourceTestResponse>> testDataSource(@RequestHeader(name="Authorization",required=false) String a,@PathVariable String id){ return PlatformResponses.ok(service.testDataSource(principal(a),id)); }
    @PostMapping("/data-sources/{id}/activate") ResponseEntity<ApiResponse<DataSourceResponse>> activateDataSource(@RequestHeader(name="Authorization",required=false) String a,@PathVariable String id){ return PlatformResponses.ok(service.activateDataSource(principal(a),id)); }
    @PostMapping("/data-sources/{id}/disable") ResponseEntity<ApiResponse<DataSourceResponse>> disableDataSource(@RequestHeader(name="Authorization",required=false) String a,@PathVariable String id){ return PlatformResponses.ok(service.disableDataSource(principal(a),id)); }
    @GetMapping("/data-source-sync-tasks") ResponseEntity<ApiResponse<List<DataSourceSyncTaskResponse>>> syncTasks(@RequestHeader(name="Authorization",required=false) String a){ return PlatformResponses.ok(service.syncTasks(principal(a))); }
    @PostMapping("/data-source-sync-tasks") ResponseEntity<ApiResponse<DataSourceSyncTaskResponse>> createSyncTask(@RequestHeader(name="Authorization",required=false) String a,@RequestBody DataSourceSyncTaskRequest r){ return PlatformResponses.ok(service.createSyncTask(principal(a),r)); }
    @PostMapping("/data-source-sync-tasks/{id}/run") ResponseEntity<ApiResponse<DataSourceSyncTaskResponse>> runSyncTask(@RequestHeader(name="Authorization",required=false) String a,@PathVariable String id){ return PlatformResponses.ok(service.runSyncTask(principal(a),id)); }
    @GetMapping("/datasets") ResponseEntity<ApiResponse<DatasetListResponse>> datasets(@RequestHeader(name="Authorization",required=false) String a,@RequestParam(required=false) String keyword,@RequestParam(required=false) String datasetType,@RequestParam(required=false) String status,@RequestParam(required=false) String accessLevel,@RequestParam(defaultValue="1") int page,@RequestParam(defaultValue="20") int pageSize){ return PlatformResponses.ok(service.datasets(principal(a),keyword,datasetType,status,accessLevel,page,pageSize)); }
    @PostMapping("/datasets") ResponseEntity<ApiResponse<DatasetDetailResponse>> createDataset(@RequestHeader(name="Authorization",required=false) String a,@RequestBody DatasetCreateRequest r){ return PlatformResponses.ok(service.createDataset(principal(a),r)); }
    @PostMapping("/dataset-upload-sessions") ResponseEntity<ApiResponse<DatasetUploadSessionResponse>> createDatasetUploadSession(@RequestHeader(name="Authorization",required=false) String a,@RequestBody DatasetUploadSessionCreateRequest r){ return PlatformResponses.ok(service.createDatasetUploadSession(principal(a),r)); }
    @PostMapping(value="/dataset-upload-sessions/{sessionId}/files", consumes=MediaType.MULTIPART_FORM_DATA_VALUE) ResponseEntity<ApiResponse<DatasetUploadSessionResponse>> uploadDatasetSessionFiles(@RequestHeader(name="Authorization",required=false) String a,@PathVariable String sessionId,@RequestPart("files") MultipartFile[] files){ return PlatformResponses.ok(service.uploadDatasetSessionFiles(principal(a),sessionId,files)); }
    @GetMapping("/dataset-upload-sessions/{sessionId}") ResponseEntity<ApiResponse<DatasetUploadSessionResponse>> datasetUploadSession(@RequestHeader(name="Authorization",required=false) String a,@PathVariable String sessionId){ return PlatformResponses.ok(service.datasetUploadSession(principal(a),sessionId)); }
    @PostMapping("/dataset-upload-sessions/{sessionId}/commit") ResponseEntity<ApiResponse<DatasetUploadSessionResponse>> commitDatasetUploadSession(@RequestHeader(name="Authorization",required=false) String a,@PathVariable String sessionId,@RequestBody(required=false) DatasetUploadSessionCommitRequest r){ return PlatformResponses.ok(service.commitDatasetUploadSession(principal(a),sessionId,r==null?new DatasetUploadSessionCommitRequest(false):r)); }
    @GetMapping("/datasets/{id}") ResponseEntity<ApiResponse<DatasetDetailResponse>> datasetDetail(@RequestHeader(name="Authorization",required=false) String a,@PathVariable String id,@RequestParam(required=false) String versionId){ return PlatformResponses.ok(service.datasetDetail(principal(a),id,versionId)); }
    @GetMapping("/datasets/{id}/annotation-candidates") ResponseEntity<ApiResponse<DatasetAnnotationCandidateResponse>> annotationCandidate(@RequestHeader(name="Authorization",required=false) String a,@PathVariable String id){ return PlatformResponses.ok(service.annotationCandidate(principal(a),id)); }
    @GetMapping("/datasets/{id}/annotation-tasks") ResponseEntity<ApiResponse<List<DatasetAnnotationTaskResponse>>> datasetAnnotationTasks(@RequestHeader(name="Authorization",required=false) String a,@PathVariable String id){ return PlatformResponses.ok(service.annotationTasks(principal(a),id)); }
    @PostMapping("/datasets/{id}/annotation-tasks") ResponseEntity<ApiResponse<AnnotationTaskDetailResponse>> createDatasetAnnotationTask(@RequestHeader(name="Authorization",required=false) String a,@PathVariable String id,@RequestBody AnnotationTaskCreateRequest r){ return PlatformResponses.ok(service.createAnnotationTask(principal(a),id,r)); }
    @PutMapping("/datasets/{id}") ResponseEntity<ApiResponse<DatasetDetailResponse>> updateDataset(@RequestHeader(name="Authorization",required=false) String a,@PathVariable String id,@RequestBody DatasetUpdateRequest r){ return PlatformResponses.ok(service.updateDataset(principal(a),id,r)); }
    @PostMapping("/datasets/{id}/versions") ResponseEntity<ApiResponse<DatasetVersionResponse>> createVersion(@RequestHeader(name="Authorization",required=false) String a,@PathVariable String id,@RequestBody(required=false) DatasetVersionCreateRequest r){ return PlatformResponses.ok(service.createVersion(principal(a),id,r==null?new DatasetVersionCreateRequest(null,null,null,null,null):r)); }
    @DeleteMapping("/datasets/{id}/versions/{vid}") ResponseEntity<ApiResponse<DatasetVersionDeleteResponse>> deleteVersion(@RequestHeader(name="Authorization",required=false) String a,@PathVariable String id,@PathVariable String vid){ return PlatformResponses.ok(service.deleteVersion(principal(a),id,vid)); }
    @PostMapping("/datasets/{id}/versions/{vid}/files") ResponseEntity<ApiResponse<DatasetFileResponse>> attachFile(@RequestHeader(name="Authorization",required=false) String a,@PathVariable String id,@PathVariable String vid,@RequestBody DatasetFileAttachRequest r){ return PlatformResponses.ok(service.attachFile(principal(a),id,vid,r)); }
    @DeleteMapping("/datasets/{id}/versions/{vid}/files/{bindingId}") ResponseEntity<ApiResponse<DatasetFileUnbindResponse>> unbindFile(@RequestHeader(name="Authorization",required=false) String a,@PathVariable String id,@PathVariable String vid,@PathVariable String bindingId){ return PlatformResponses.ok(service.unbindFile(principal(a),id,vid,bindingId)); }
    @PostMapping("/datasets/{id}/versions/{vid}/publish") ResponseEntity<ApiResponse<DatasetVersionResponse>> publishVersion(@RequestHeader(name="Authorization",required=false) String a,@PathVariable String id,@PathVariable String vid){ return PlatformResponses.ok(service.publishVersion(principal(a),id,vid)); }
    @PostMapping("/datasets/{id}/archive") ResponseEntity<ApiResponse<DatasetSummaryResponse>> archiveDataset(@RequestHeader(name="Authorization",required=false) String a,@PathVariable String id){ return PlatformResponses.ok(service.archiveDataset(principal(a),id)); }
    @DeleteMapping("/datasets/{id}") ResponseEntity<ApiResponse<Void>> deleteDataset(@RequestHeader(name="Authorization",required=false) String a,@PathVariable String id){ service.deleteDataset(principal(a),id); return PlatformResponses.ok(null); }
    @GetMapping("/datasets/{id}/lineage") ResponseEntity<ApiResponse<List<DataLineageResponse>>> lineage(@RequestHeader(name="Authorization",required=false) String a,@PathVariable String id){ return PlatformResponses.ok(service.datasetLineage(principal(a),id)); }
    @GetMapping("/datasets/{id}/access") ResponseEntity<ApiResponse<List<DatasetAccessRequestResponse>>> access(@RequestHeader(name="Authorization",required=false) String a,@PathVariable String id){ return PlatformResponses.ok(service.accessRequests(principal(a),id)); }
    @GetMapping("/dataset-access-requests") ResponseEntity<ApiResponse<List<DatasetAccessRequestResponse>>> accessRequestInbox(@RequestHeader(name="Authorization",required=false) String a,@RequestParam(required=false) String status,@RequestParam(required=false) String datasetId){ return PlatformResponses.ok(service.accessRequestInbox(principal(a),status,datasetId)); }
    @PostMapping("/datasets/{id}/access-requests") ResponseEntity<ApiResponse<DatasetAccessRequestResponse>> requestAccess(@RequestHeader(name="Authorization",required=false) String a,@PathVariable String id,@RequestBody DatasetAccessRequestCreateRequest r){ return PlatformResponses.ok(service.requestAccess(principal(a),id,r)); }
    @PutMapping("/dataset-access-requests/{id}/approve") ResponseEntity<ApiResponse<DatasetAccessGrantResponse>> approveAccess(@RequestHeader(name="Authorization",required=false) String a,@PathVariable String id,@RequestBody(required=false) DatasetAccessReviewRequest r){ return PlatformResponses.ok(service.approveAccess(principal(a),id,r==null?new DatasetAccessReviewRequest(null,null):r)); }
    @PutMapping("/dataset-access-requests/{id}/reject") ResponseEntity<ApiResponse<DatasetAccessRequestResponse>> rejectAccess(@RequestHeader(name="Authorization",required=false) String a,@PathVariable String id,@RequestBody(required=false) DatasetAccessReviewRequest r){ return PlatformResponses.ok(service.rejectAccess(principal(a),id,r==null?new DatasetAccessReviewRequest(null,null):r)); }
    @GetMapping("/dataset-references") ResponseEntity<ApiResponse<DatasetReferenceResponse>> ref(@RequestHeader(name="Authorization",required=false) String a,@RequestParam String datasetId,@RequestParam(required=false) String versionId){ return PlatformResponses.ok(service.reference(principal(a),datasetId,versionId)); }
    @GetMapping("/data-standards/overview") ResponseEntity<ApiResponse<DataStandardOverviewResponse>> dataStandardOverview(@RequestHeader(name="Authorization",required=false) String a){ return PlatformResponses.ok(service.dataStandardOverview(principal(a))); }
    @GetMapping("/datasets/{id}/standard-profile") ResponseEntity<ApiResponse<DataStandardProfileResponse>> dataStandardProfile(@RequestHeader(name="Authorization",required=false) String a,@PathVariable String id){ return PlatformResponses.ok(service.dataStandardProfile(principal(a),id)); }
    @GetMapping("/data-standard-tasks") ResponseEntity<ApiResponse<List<DataStandardTaskResponse>>> dataStandardTasks(@RequestHeader(name="Authorization",required=false) String a){ return PlatformResponses.ok(service.dataStandardTasks(principal(a))); }
    @PostMapping("/data-standard-tasks") ResponseEntity<ApiResponse<DataStandardTaskResponse>> createDataStandardTask(@RequestHeader(name="Authorization",required=false) String a,@RequestBody DataStandardTaskRequest r){ return PlatformResponses.ok(service.createDataStandardTask(principal(a),r)); }
    @PostMapping("/data-standard-tasks/{id}/run") ResponseEntity<ApiResponse<DataStandardTaskResponse>> runDataStandardTask(@RequestHeader(name="Authorization",required=false) String a,@PathVariable String id){ return PlatformResponses.ok(service.runDataStandardTask(principal(a),id)); }
    private PlatformPrincipal principal(String authorization){ return identityService.requirePrincipal(authorization); }
}
