server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location /api/ {
    proxy_pass http://smp-backend:8080/api/;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
