apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "yfind-aiplatform.fullname" . }}-ai-adapter
  labels:
    app.kubernetes.io/component: ai-adapter
spec:
  replicas: {{ .Values.aiAdapter.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: ai-adapter
  template:
    metadata:
      labels:
        app.kubernetes.io/component: ai-adapter
    spec:
      containers:
        - name: ai-adapter
          image: "{{ .Values.aiAdapter.image.repository }}:{{ .Values.aiAdapter.image.tag }}"
          imagePullPolicy: {{ .Values.aiAdapter.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.aiAdapter.service.port }}
          env:
            - name: AI_ADAPTER_LABEL_STUDIO_URL
              value: {{ .Values.aiAdapter.env.AI_ADAPTER_LABEL_STUDIO_URL | quote }}
            - name: AI_ADAPTER_MLFLOW_URL
              value: {{ .Values.aiAdapter.env.AI_ADAPTER_MLFLOW_URL | quote }}
            - name: AI_ADAPTER_WORKFLOW_ENGINE_URL
              value: {{ .Values.aiAdapter.env.AI_ADAPTER_WORKFLOW_ENGINE_URL | quote }}
            - name: AI_ADAPTER_KSERVE_URL
              value: {{ .Values.aiAdapter.env.AI_ADAPTER_KSERVE_URL | quote }}
            - name: AI_ADAPTER_OBJECT_STORAGE_ENDPOINT
              value: {{ .Values.aiAdapter.env.AI_ADAPTER_OBJECT_STORAGE_ENDPOINT | quote }}
          readinessProbe:
            httpGet:
              path: /internal/health
              port: {{ .Values.aiAdapter.service.port }}
