apiVersion: v1
kind: Service
metadata:
  name: {{ include "yfind-aiplatform.fullname" . }}-frontend
spec:
  selector:
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
