CREATE TABLE IF NOT EXISTS platform_domain_events (
  event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  domain_key VARCHAR(80) NOT NULL,
  aggregate_key VARCHAR(160) NOT NULL,
  event_type VARCHAR(120) NOT NULL,
  payload TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_platform_domain_events_domain ON platform_domain_events(domain_key, event_id);
CREATE INDEX IF NOT EXISTS idx_platform_domain_events_aggregate ON platform_domain_events(domain_key, aggregate_key, event_id);