import { test, expect } from '@playwright/test';
import { seedAuthenticatedSession } from './helpers';

test('TASK-annotation-integration AC-01 AC-02 AC-03 annotation task list and local workbench entry', async ({ page }) => {
  await seedAuthenticatedSession(page);
  await page.getByText('标注任务').click();
  await expect(page.getByRole('heading', { name: '标注任务管理' })).toBeVisible();
  await expect(page.getByText('焊缝缺陷检测标注任务')).toBeVisible();
  await expect(page.getByRole('button', { name: '标签模板' })).toBeVisible();
  await expect(page.getByText(/本地标注模式/)).toBeVisible();
  await expect(page.getByText('焊缝视频抽帧预处理结果')).toBeVisible();

  await page.getByRole('button', { name: '＋ 新建标注任务' }).click();
  await page.getByLabel('标注场景').click();
  await expect(page.locator('.ant-select-dropdown:visible')).toContainText('IMAGE_TAGGING');
  await expect(page.locator('.ant-select-dropdown:visible')).toContainText('IMAGE_SEGMENTATION');
  await expect(page.locator('.ant-select-dropdown:visible')).not.toContainText(/TEXT_LABELING|文本分类|语音|视频逐帧|多模态/);
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'Close' }).click();
  await expect(page.locator('a', { hasText: '同步' })).toHaveCount(0);
});

test('TASK-visual-preprocess-operators-pipeline AC-04 AC-05 AC-08 AC-09 preprocessed dataset annotation source eligibility', async ({ page }) => {
  await seedAuthenticatedSession(page);
  await page.getByText('标注任务').click();
  await expect(page.getByRole('heading', { name: '标注任务管理' })).toBeVisible();

  await page.getByRole('button', { name: '＋ 新建标注任务' }).click();
  await expect(page.getByLabel('源数据集（仅 ACTIVE 且可标注图片数据集）')).toBeVisible();
  await page.getByLabel('源数据集（仅 ACTIVE 且可标注图片数据集）').click();
  await expect(page.locator('.ant-select-dropdown:visible')).toContainText('焊缝视频抽帧预处理结果');
  await expect(page.locator('.ant-select-dropdown:visible')).toContainText('预处理后/图片');
  await page.keyboard.press('Escape');

  await page.getByLabel('源数据集（仅 ACTIVE 且可标注图片数据集）').click();
  await page.getByText('焊缝视频抽帧预处理结果').last().click();
  await page.getByRole('button', { name: '创建任务' }).click();
  await expect(page.getByText('标注任务已创建')).toBeVisible();
});

test('TASK-annotation-integration AC-04 AC-05 workbench draft submit flow', async ({ page }) => {
  await seedAuthenticatedSession(page);
  await page.getByText('标注工作台').click();
  await expect(page.getByRole('heading', { name: '标注工作台' })).toBeVisible();
  await expect(page.getByLabel('样本队列')).toBeVisible();
  await expect(page.getByLabel('原生标注画布')).toBeVisible();
  await expect(page.getByTestId('annotation-industrial-image')).toBeVisible();
  await expect(page.getByTestId('annotation-sample-caption')).toContainText('Industrial');
  await expect(page.locator('.annotation-thumb-image img').first()).toBeVisible();
  await expect(page.getByText('焊接气孔').first()).toBeVisible();
  await expect(page.getByText('裂纹').first()).toBeVisible();
  await expect(page.getByText('夹渣').first()).toBeVisible();
  await expect(page.getByText('未熔合').first()).toBeVisible();
  await expect(page.getByText('当前框属性')).toBeVisible();
  await expect(page.getByText('快捷键').first()).toBeVisible();
  await expect(page.getByText(/拖拽绘制框/)).toBeVisible();
  await page.getByTestId('annotation-box-ai-suggestion-crack-001').click();
  await expect(page.getByTestId('annotation-box-count')).toHaveText('7');
  await page.keyboard.press('D');
  await expect(page.getByTestId('annotation-box-count')).toHaveText('6');
  await page.getByTestId('annotation-box-ai-suggestion-fusion-001').click();
  const aiRect = await page.getByTestId('annotation-box-ai-suggestion-fusion-001').boundingBox();
  expect(aiRect).not.toBeNull();
  await page.mouse.move(aiRect!.x + aiRect!.width / 2, aiRect!.y + aiRect!.height / 2);
  await page.mouse.down();
  await page.mouse.move(aiRect!.x + aiRect!.width / 2 + 40, aiRect!.y + aiRect!.height / 2 + 40, { steps: 4 });
  await page.mouse.up();
  await expect(page.getByText('坐标：').locator('..')).not.toContainText('(170, 60)');
  await page.keyboard.press('2');
  await expect(page.getByRole('button', { name: /裂纹\s+2/ })).toHaveAttribute('aria-pressed', 'true');
  await page.keyboard.press('W');
  await expect(page.getByText(/已新增标注框：裂纹/).last()).toBeVisible();
  await expect(page.getByTestId('annotation-box-count')).toHaveText('7');
  await page.keyboard.press('E');
  await expect(page.getByText(/已新增标注框：裂纹/).last()).toBeVisible();
  await expect(page.getByTestId('annotation-box-count')).toHaveText('8');
  await expect(page.getByTestId('annotation-current-shape')).toHaveText('椭圆');
  await page.keyboard.press('P');
  await expect(page.getByText(/已新增标注框：裂纹/).last()).toBeVisible();
  await expect(page.getByTestId('annotation-box-count')).toHaveText('9');
  await expect(page.getByTestId('annotation-current-shape')).toHaveText('多边形');
  await page.getByLabel('焊缝缺陷标注画布').focus();
  await page.keyboard.press('Control+Z');
  await expect(page.getByTestId('annotation-box-count')).toHaveText('8');
  await page.getByRole('button', { name: '撤销 Ctrl+Z' }).click();
  await expect(page.getByTestId('annotation-box-count')).toHaveText('7');
  await page.getByRole('button', { name: '重做 Ctrl+Y' }).click();
  await expect(page.getByTestId('annotation-box-count')).toHaveText('8');
  const crackBox = page.getByTestId('annotation-box-box-crack-001');
  const crackRect = await crackBox.boundingBox();
  expect(crackRect).not.toBeNull();
  await page.mouse.move(crackRect!.x + crackRect!.width / 2, crackRect!.y + crackRect!.height / 2);
  await page.mouse.down();
  await page.mouse.move(crackRect!.x + crackRect!.width / 2 + 80, crackRect!.y + crackRect!.height / 2 + 70, { steps: 6 });
  await page.mouse.up();
  await expect(page.getByText('坐标：').locator('..')).not.toContainText('(240, 110)');
  await page.keyboard.press('D');
  await expect(page.getByTestId('annotation-box-count')).toHaveText('7');
  await page.getByRole('button', { name: '撤销 Ctrl+Z' }).click();
  await expect(page.getByTestId('annotation-box-count')).toHaveText('8');
  await page.getByRole('button', { name: '快捷键 ?' }).click();
  await expect(page.getByText('快捷键参考')).toBeVisible();
  await page.getByRole('button', { name: 'Close' }).click();
  await expect(page.getByRole('button', { name: /同步/ })).toHaveCount(0);
  const draftResponse = page.waitForRequest((request) => request.url().includes('/api/v1/annotation/work-items/AWI-WELD-001/draft') && request.method() === 'POST');
  await page.getByRole('button', { name: '保存标注' }).click();
  const draftBody = JSON.parse((await draftResponse).postData() ?? '{}');
  const savedBoxes = JSON.parse(draftBody.annotationJson).boxes;
  expect(savedBoxes.length).toBe(8);
  expect(savedBoxes.some((box: { shape?: string }) => box.shape === 'ellipse')).toBeTruthy();
  await expect(page.getByText('草稿已保存')).toBeVisible();
  await page.getByRole('button', { name: '提交审核' }).click();
  await expect(page.getByText('标注结果已提交，等待审核')).toBeVisible();
});

test('TASK-annotation-integration AC-06 AC-07 AC-08 AC-09 review quality and publication flow', async ({ page }) => {
  await seedAuthenticatedSession(page);
  await page.getByText('标注审核').click();
  await expect(page.getByRole('heading', { name: '标注审核' })).toBeVisible();
  await expect(page.getByText(/DAT-004/)).toBeVisible();
  await expect(page.getByRole('button', { name: /导入/ })).toHaveCount(0);
  const qualityResponse = page.waitForResponse((response) => response.url().includes('/api/v1/annotation/tasks/ANN-WELD-Q2/quality-check') && response.request().method() === 'POST');
  await page.getByRole('button', { name: '质量检查' }).click();
  const qualityBody = await (await qualityResponse).json();
  expect(qualityBody.data.diagnosticMessage).toContain('DAT-010 quality passed');
  const publishResponse = page.waitForResponse((response) => response.url().includes('/api/v1/annotation/tasks/ANN-WELD-Q2/publish-dataset') && response.request().method() === 'POST');
  await page.getByRole('button', { name: '发布标注数据集' }).click();
  const publishBody = await (await publishResponse).json();
  expect(publishBody.data.outputDatasetId).toBe('DATASET-WELD-ANNOTATED');
  expect(publishBody.data.annotationArtifactFileId).toBe('FILE-ANN-WELD-Q2');
  expect(publishBody.data.annotationArtifactRole).toBe('ANNOTATION_RESULT');
  await expect(page.getByText(/标注文件：FILE-ANN-WELD-Q2/)).toBeVisible();
});
